USE COMMERCIAL_DB
GO

-- Creating table
IF OBJECT_ID('T_SALES') IS NULL
BEGIN

CREATE TABLE T_SALES
(
    DOCUMENT_NUMBER	 NUMERIC(15)
  , COMPANY_CODE     NUMERIC(15)
  , CUSTOMER_CODE    NUMERIC(15)
  , SALESMAN_CODE    NUMERIC(15)
  , TRANSACTION_DATE DATE
  , PRODUCT_CODE     NUMERIC(15)
  , QUANTITY         INT
  , GROSS_SALES      MONEY
  , TOTAL_DISCOUNT   MONEY
  , NET_SALES       MONEY
)

END
